==== START logs for container s3-csi-controller of pod kube-system/s3-csi-controller-7589d96658-2f7hc ====
I0903 12:23:15.144465       1 driver.go:137] Driver version: 1.2.0, Git commit: cfd7c8aa614d5235d9817f97f2bf04164c00e86c, build date: 2025-09-03T12:19:18Z, nodeID: controller, mount-s3 version: 1.18.0, kubernetes version: v1.32.0
I0903 12:23:15.144533       1 driver.go:148] Running in controller-only mode, skipping mounter initialization
I0903 12:23:15.144721       1 driver.go:243] Listening for connections on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}
==== END logs for container s3-csi-controller of pod kube-system/s3-csi-controller-7589d96658-2f7hc ====
==== START logs for container csi-provisioner of pod kube-system/s3-csi-controller-7589d96658-2f7hc ====
I0903 12:23:19.481163       1 feature_gate.go:385] feature gates: {map[]}
I0903 12:23:19.481265       1 csi-provisioner.go:168] "Version" version="v5.3.0"
I0903 12:23:19.481272       1 csi-provisioner.go:191] Building kube configs for running in cluster...
I0903 12:23:19.481459       1 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0903 12:23:19.481475       1 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0903 12:23:19.481480       1 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0903 12:23:19.481483       1 envvar.go:172] "Feature gate default state" feature="InOrderInformers" enabled=true
I0903 12:23:19.481487       1 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0903 12:23:19.482472       1 common.go:143] "Probing CSI driver for readiness"
I0903 12:23:19.484022       1 csi-provisioner.go:246] Detected CSI driver s3.csi.scality.com
I0903 12:23:19.485675       1 csi-provisioner.go:318] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I0903 12:23:19.486017       1 controller.go:758] "Using saving PVs to API server in background"
I0903 12:23:19.490881       1 reflector.go:430] "Caches populated" type="*v1.PersistentVolumeClaim" reflector="k8s.io/client-go/informers/factory.go:160"
I0903 12:23:19.490929       1 reflector.go:430] "Caches populated" type="*v1.StorageClass" reflector="k8s.io/client-go/informers/factory.go:160"
I0903 12:23:19.586885       1 controller.go:838] "Starting provisioner controller" component="s3.csi.scality.com_s3-csi-controller-7589d96658-2f7hc_e91083c3-2a60-46a4-aa33-45d4b287ec21"
I0903 12:23:19.586931       1 volume_store.go:98] "Starting save volume queue"
I0903 12:23:19.588701       1 reflector.go:430] "Caches populated" type="*v1.PersistentVolume" reflector="sigs.k8s.io/sig-storage-lib-external-provisioner/v11/controller/controller.go:872"
I0903 12:23:19.588721       1 reflector.go:430] "Caches populated" type="*v1.StorageClass" reflector="sigs.k8s.io/sig-storage-lib-external-provisioner/v11/controller/controller.go:875"
I0903 12:23:19.688546       1 controller.go:887] "Started provisioner controller" component="s3.csi.scality.com_s3-csi-controller-7589d96658-2f7hc_e91083c3-2a60-46a4-aa33-45d4b287ec21"
I0903 12:23:26.150429       1 event.go:389] "Event occurred" object="s3-advanced-patterns-2191/reclaim-pvc-d68727cf" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-2191/reclaim-pvc-d68727cf\""
I0903 12:23:26.157081       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=0
E0903 12:23:26.157136       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified" logger="UnhandledError"
I0903 12:23:26.157245       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-8643/invalid-pvc-716b4422\""
I0903 12:23:26.157367       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified"
I0903 12:23:26.159293       1 event.go:389] "Event occurred" object="s3-advanced-patterns-6517/cred-fallback-pvc-no-secrets-c26daa6f" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-6517/cred-fallback-pvc-no-secrets-c26daa6f\""
I0903 12:23:26.160167       1 event.go:389] "Event occurred" object="volume-14/s3.csi.scality.com9pjcf" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"volume-14/s3.csi.scality.com9pjcf\""
I0903 12:23:26.193955       1 controller.go:959] successfully created PV pvc-f6d6c891-9ca8-41be-9bfe-65ee4fb4876f for PVC s3.csi.scality.com9pjcf and csi volume name csi-s3-574975ae-432c-4b4c-85ef-363abd3340e9
I0903 12:23:26.194009       1 controller.go:959] successfully created PV pvc-838aab36-5044-4965-852d-29c302d223e6 for PVC cred-fallback-pvc-no-secrets-c26daa6f and csi volume name csi-s3-107238cb-672d-4741-a018-435f71100672
I0903 12:23:26.194390       1 controller.go:959] successfully created PV pvc-29bc5d13-0d82-472b-a2e6-f889729206fa for PVC reclaim-pvc-d68727cf and csi volume name csi-s3-0705d72a-edfe-4569-95a9-1751e733cd8c
I0903 12:23:26.196772       1 event.go:389] "Event occurred" object="s3-advanced-patterns-6517/cred-fallback-pvc-no-secrets-c26daa6f" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ProvisioningSucceeded" message="Successfully provisioned volume pvc-838aab36-5044-4965-852d-29c302d223e6"
I0903 12:23:26.196810       1 event.go:389] "Event occurred" object="s3-advanced-patterns-2191/reclaim-pvc-d68727cf" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ProvisioningSucceeded" message="Successfully provisioned volume pvc-29bc5d13-0d82-472b-a2e6-f889729206fa"
I0903 12:23:26.197695       1 event.go:389] "Event occurred" object="volume-14/s3.csi.scality.com9pjcf" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ProvisioningSucceeded" message="Successfully provisioned volume pvc-f6d6c891-9ca8-41be-9bfe-65ee4fb4876f"
I0903 12:23:27.157818       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=1
E0903 12:23:27.157856       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified" logger="UnhandledError"
I0903 12:23:27.157889       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-8643/invalid-pvc-716b4422\""
I0903 12:23:27.157917       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified"
I0903 12:23:29.158690       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=2
E0903 12:23:29.158720       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified" logger="UnhandledError"
I0903 12:23:29.158766       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-8643/invalid-pvc-716b4422\""
I0903 12:23:29.158798       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified"
I0903 12:23:33.159668       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=3
E0903 12:23:33.159709       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified" logger="UnhandledError"
I0903 12:23:33.159749       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-8643/invalid-pvc-716b4422\""
I0903 12:23:33.159776       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified"
I0903 12:23:41.160314       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=4
E0903 12:23:41.160352       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified" logger="UnhandledError"
I0903 12:23:41.160394       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-8643/invalid-pvc-716b4422\""
I0903 12:23:41.160412       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified"
I0903 12:23:56.161572       1 event.go:389] "Event occurred" object="s3-advanced-patterns-6413/wait-pvc-fa2d03a0" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-6413/wait-pvc-fa2d03a0\""
I0903 12:23:56.201704       1 controller.go:959] successfully created PV pvc-0791ca10-4c1c-4048-9c8a-62005baeb355 for PVC wait-pvc-fa2d03a0 and csi volume name csi-s3-823ce60e-32f2-46e1-921d-4f8da31fb353
I0903 12:23:56.204139       1 event.go:389] "Event occurred" object="s3-advanced-patterns-6413/wait-pvc-fa2d03a0" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ProvisioningSucceeded" message="Successfully provisioned volume pvc-0791ca10-4c1c-4048-9c8a-62005baeb355"
I0903 12:23:57.161049       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=5
E0903 12:23:57.161096       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified" logger="UnhandledError"
I0903 12:23:57.161105       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"s3-advanced-patterns-8643/invalid-pvc-716b4422\""
I0903 12:23:57.161146       1 event.go:389] "Event occurred" object="s3-advanced-patterns-8643/invalid-pvc-716b4422" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="failed to provision volume with StorageClass \"invalid-sc-82492ede\": failed to get name and namespace template from params: either name and namespace for Provisioner secrets specified, Both must be specified"
I0903 12:24:29.161209       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=6
E0903 12:24:29.161241       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": storageClass \"invalid-sc-82492ede\" not found" logger="UnhandledError"
I0903 12:24:31.208212       1 controller.go:965] "Retrying syncing claim" key="f76fa743-f85e-4546-a8e6-69f85252c192" failures=7
E0903 12:24:31.208261       1 controller.go:988] "Unhandled Error" err="error syncing claim \"f76fa743-f85e-4546-a8e6-69f85252c192\": storageClass \"invalid-sc-82492ede\" not found" logger="UnhandledError"
E0903 12:25:33.161610       1 controller.go:1058] "Unhandled Error" err="claim \"f76fa743-f85e-4546-a8e6-69f85252c192\" in work queue no longer exists" logger="UnhandledError"
I0903 12:25:36.324037       1 controller.go:1317] volume pvc-838aab36-5044-4965-852d-29c302d223e6 does not need any deletion secrets
E0903 12:27:57.970499       1 controller.go:1313] failed to get credentials for volume pvc-0791ca10-4c1c-4048-9c8a-62005baeb355: error getting secret test-provisioner-secret-89021e7b in namespace s3-advanced-patterns-6413: secrets "test-provisioner-secret-89021e7b" not found
==== END logs for container csi-provisioner of pod kube-system/s3-csi-controller-7589d96658-2f7hc ====
